# 공통설정
server:
  port: 8082

spring:
  main:
    allow-bean-definition-overriding: true
  output:
    ansi:
      enabled: always
  jackson: property-naming-strategy:SNAKE_CASE

# 로그레벨의 설정  쿼리 및 결과의 로그 출력 레벨 조정이 가능
logging:
  level:
    com.kakao.platform: DEBUG

# log설정
log:
  path: /log/pushServer/api
  name: api.log
  pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%-5level] [%X{identity}] %msg %n"
  appender: console

---
## DEV
spring:
  profiles: dev

---
## PROD
spring:
  profiles: prod